[helpers]

[default]
depends = []

[default.files]
"alsoft.conf" = "~/.config/alsoft.conf"
bluetuith = "~/.config/bluetuith"
btop = { target = "~/.config/btop", type = "template" }
dunst = "~/.config/dunst"
fish = "~/.config/fish"
kitty = "~/.config/kitty"
mangohud = "~/.config/MangoHud"
"mangohud/beefd-font-patched.otf" = { target = "~/.config/MangoHud/beefd-font-patched.otf", type = "symbolic" }
nemo = "~/.config/nemo"
"nvim/lua/chadrc.lua" = { target = "~/.config/nvim/lua/chadrc.lua", type = "template" }
nix = "~/.config/nix"
nvim = "~/.config/nvim"
"pavucontrol.ini" = "~/.config/pavucontrol.ini"
"starship.toml" = "~/.config/starship.toml"
tmux = "~/.config/tmux"
"user-dirs/user-dirs.dirs" = "~/.config/user-dirs.dirs"
"user-dirs/user-dirs.locale" = "~/.config/user-dirs.locale"
wallust = { target = "~/.config/wallust", type = "symbolic" } 
yt-dlp = "~/.config/yt-dlp" 

[default.variables]
cursor = true
use-vrr = 0
app-scale = 1.0

[hyprland.files]
hypr = "~/.config/hypr"
waybar = "~/.config/waybar"

[hyprland.variables]
hyprland-monitor-line = "auto, highrr, auto, 1.0, bitdepth, 8"
hyprland-git = false
waybar-battery = true
ps-adapter-battery = false
taskbar-bt-battery = false

[intel]

[nvidia]

[openrgb]

[sunshine]

[uxplay]

[udiskie]

[wayvnc]
